sudo: false
language: java
jdk:
  - oraclejdk8
install:
  - ./gradlew build
script:
  - ./gradlew jacocoTestReport
after_success:
  - ./gradlew coveralls
cache:
  directories:
  - $HOME/.gradle
#notifications:
#  slack:
#    secure: KB9ef2UZyW0YRKc8YmEPtvn7Y49LJJPcTNSPMlpZetvMWLVYZzSkBwsZg2nkdAMeaYTmdkHYbsXbfy35FSY3+yCp3ULrmbRl/uQmviLBJC3CadKZBCx5236ZboCY10341AC5nMvfkcB7OJAoS6tN7EKU5IdWhPvK+6r1fl83fLw=
